---
- name: playbook Install Docker
  hosts: ansible_client
  remote_user: tzahi
  become: true
  tasks:

  - name: Add specified repository into sources list
    apt_repository:
      repo:  'deb https://download.docker.com/linux/ubuntu xenial stable/'
      state: present
      update_cache: yes