---
- name: playbook-install-jenkins
  hosts: ansible_client
  remote_user: tzahi
  become: true
  tasks:

  - name: Update APT package manager repositories and installing openjdk-8-jdk
    apt:
      name: openjdk-8-jdk
      update_cache: yes