---
- name: test playbook
  hosts: ansible_client
  remote_user: root
  become: true 
  tasks:
    - name: install httpd
      apt:
          name: apache2
          state: present
    - name: run httpd
      service:
              name: httpd
              state: started
    - name: create content
      copy:
            content: "Congrats on installing Ansible"
            dest: /var/www/html/index.html