---
- name: Ansible Playbook Install Hashicorp Tools
  remote_user: tzahi
  become: true
  tasks:

  - name: Add Hashicorp's official GPG key
    shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -


  - name: Add Specified Repository into Sources List and Run apt-get update
    apt_repository:
      repo:  "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      state: present
      update_cache: yes
      
    - name: Install all the packages
    apt: name={{ item }} 
    state: installed
    update_cache: yes
    with_items:
       - vault
       - terraform
       - packer
