---
- name: TEST - Download puppet-agent deb File to tmp Folder
  hosts: all
  become: true
  tasks:

  - name: Download puppet-agent deb File
    get_url:
      url: https://apt.puppetlabs.com/puppet5-release-wheezy.deb
      dest: /tmp/
      mode: '0744'
