- name: Update APT package manager repositories and installing openjdk-8-jdk
  apt:
    name: openjdk-8-jdk
    update_cache: yes

- name: Add an apt key for Jenkins
  apt_key:
    keyserver: pkg.jenkins.io/debian-stable/jenkins.io.key
    id: 62A9756BFD780C377CF24BA8FCEF32E745F2C3D5

- name: Add specified repository into sources list and run apt-get update
  apt_repository:
    repo:  'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
    update_cache: yes

- name: Installing Jenkins
  apt:
    name: jenkins
    state: present

- name: Starting The jenkins Service
  systemd:
    name: jenkins
    state: started
    enabled: yes
