- name: Add Official GPG Key for Vault Repository
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Vault Repository into Sources List and Run apt-get update
  apt_repository:
    repo:  "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present
    update_cache: yes
  
- name: Update APT package manager repositories and installing Vault
  apt:
    name: vault
    update_cache: yes