---
- name: Installing Consul & Nomad Playbook
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:

 # - name: Update all packages to their latest version
 #   apt:
 #     name: "*"
 #     state: latest

  - name: Add Hashicorp official GPG key
    shell: wget https://raw.githubusercontent.com/mjhfvi/Ansible-Examples/main/aws/nginx.nomad
    args:
      warn: false

  - name: Download Nomad Job File
    shell: wget https://raw.githubusercontent.com/mjhfvi/Ansible-Examples/main/aws/nginx.nomad
    args:
      warn: false
      
  - name: Add Hashicorp Repository to APT Sources
    shell: "echo deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main > /etc/apt/sources.list.d/hashicorp.list"

  - name: Update APT cache
    become: true
    become_user: root
    apt:
      update_cache: yes

  - name: Update APT and Install Hashicorp Docker Packages 
    apt:
      pkg:
      - consul
      - nomad
      - docker
      - python3
      - python3-pip
 
  - name: Install Docker Module for Python
    pip:
      name: 
      - docker-py
    
  - name: Start nomad Service 
    ansible.builtin.service:
     name: nomad
     state: started

  - name: Run Nomad Job File
    shell: nomad run nginx.nomad
