---
- name: Installing Consul & Nomad Playbook
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:

 # - name: Update all packages to their latest version
 #   apt:
 #     name: "*"
 #     state: latest

  - name: Add Hashicorp official GPG key
    shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    args:
      warn: false

  - name: Add Hashicorp Repository to APT Sources
    shell: "echo deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main > /etc/apt/sources.list.d/hashicorp.list"

  - name: Update APT cache
    become: true
    become_user: root
    apt:
      update_cache: yes

  - name: Update APT and Install Hashicorp Packages
    apt:
      update_cache: yes
      state: latest
      pkg:
      - consul
      - nomad

  - name: Update APT and Install docker
    apt:  
      update_cache: yes
      state: latest 
      pkg:
      - docker
      
  - name: pull an image
    docker_image:
      name: nginx
    
  - name: Start nomad Service 
    ansible.builtin.service:
     name: nomad
      state: started

  - name: Download Nomad Job File
    shell: wget https://raw.githubusercontent.com/mjhfvi/Ansible-Examples/main/aws/nginx.nomad  
    args:
      warn: false

  - name: Run Nomad Job File
    shell: nomad run nginx.nomad 
    args:
      warn: false
