---
- name: Tasks to download file
  hosts: Jenkins_Node
  tasks:
  
    - name: Download jar File
      get_url:
        url: http://192.168.50.102:8080/jnlpJars/agent.jar
        dest: /tmp/
        mode: '0440'