---
- name: PlayBook To Install Grafana Server on Ubuntu
  hosts: grafana_server
  remote_user: tzahi
  become: true
  tasks:

  - name: import the Grafana apt key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
    become: true

  - name: Add Grafana Repository into sources list and run apt-get update
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      update_cache: yes

  - name: Installing Grafana Package
    apt:
      name: grafana
      state: present
      update_cache: yes

  - name: Starting The Grafana Service
    systemd:
      name: grafana-server
      state: started
      enabled: yes
