# roles/example/tasks/main.yml
- name: Install the correct web server for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

# roles/example/tasks/redhat.yml
- name: Install tree
  ansible.builtin.yum:
    name: "tree"
    state: present

# roles/example/tasks/debian.yml
- name: Install tree
  ansible.builtin.apt:
    name: "tree"
    state: present